version: "3"

services:
  redis:
     image: redis:alpine
     ports:
       - 27000:27000
  postgres:
     image: postgres
     ports:
       - 7000:7000
     environment:
       - DB_USER=postgres
       - DB_PASSWORD=docker
    mongo:
        url:
        - MONGO_URL=mongodb://localhost:27017/gobarber
